import type { AppData, BehaviorDefinition, Reward } from './types';

export const BEHAVIORS: BehaviorDefinition[] = [
  {
    id: 'morning-ready',
    label: 'Je me prépare le matin sans crier ni faire du bruit exprès',
    shortLabel: 'Préparation du matin',
    points: 5,
    type: 'check',
    section: 'essential',
    icon: 'sun',
    hint: 'Une fois le matin',
  },
  {
    id: 'homework-calm',
    label: 'Je fais mes devoirs sans rouspéter',
    shortLabel: 'Devoirs sans rouspéter',
    points: 5,
    type: 'check',
    section: 'essential',
    icon: 'book',
    hint: 'Une fois par jour de devoirs',
  },
  {
    id: 'meal-breakfast',
    label: 'Petit-déjeuner : je reste assis sans chanter ni parler fort',
    shortLabel: 'Petit-déjeuner calme',
    points: 5,
    type: 'check',
    section: 'meal',
    icon: 'coffee',
    hint: 'Au petit-déjeuner',
  },
  {
    id: 'meal-lunch',
    label: 'Déjeuner : je reste assis sans chanter ni parler fort',
    shortLabel: 'Déjeuner calme',
    points: 5,
    type: 'check',
    section: 'meal',
    icon: 'sandwich',
    hint: 'Au déjeuner',
  },
  {
    id: 'meal-dinner',
    label: 'Dîner : je reste assis sans chanter ni parler fort',
    shortLabel: 'Dîner calme',
    points: 5,
    type: 'check',
    section: 'meal',
    icon: 'utensils',
    hint: 'Au dîner',
  },
  {
    id: 'obey-first',
    label: "J'obéis à la première demande d'un adulte",
    shortLabel: 'Première demande',
    points: 3,
    type: 'counter',
    section: 'counters',
    icon: 'sparkle',
    hint: 'À chaque action réussie',
  },
  {
    id: 'care-objects',
    label: 'Je prends soin des objets de la maison (pas de coups, pas de casse)',
    shortLabel: 'Soin des objets',
    points: 2,
    type: 'check',
    section: 'essential',
    icon: 'home',
    hint: 'Bilan unique en fin de journée',
  },
  {
    id: 'siblings-morning',
    label: 'Le matin, je parle à mon frère et ma sœur avec respect, sans surnom moqueur',
    shortLabel: 'Fratrie · matin',
    points: 6,
    type: 'check',
    section: 'relationships',
    icon: 'users',
    hint: 'Bilan du matin',
  },
  {
    id: 'siblings-afternoon',
    label: "L'après-midi, je parle à mon frère et ma sœur avec respect, sans surnom moqueur",
    shortLabel: 'Fratrie · après-midi',
    points: 6,
    type: 'check',
    section: 'relationships',
    icon: 'users',
    hint: "Bilan de l'après-midi",
  },
  {
    id: 'siblings-evening',
    label: 'Le soir, je parle à mon frère et ma sœur avec respect, sans surnom moqueur',
    shortLabel: 'Fratrie · soir',
    points: 6,
    type: 'check',
    section: 'relationships',
    icon: 'users',
    hint: 'Bilan du soir',
  },
  {
    id: 'parents-morning',
    label: 'Le matin, je respecte et ne provoque pas mes parents',
    shortLabel: 'Parents · matin',
    points: 6,
    type: 'check',
    section: 'relationships',
    icon: 'heart',
    hint: 'Bilan du matin',
  },
  {
    id: 'parents-afternoon',
    label: "L'après-midi, je respecte et ne provoque pas mes parents",
    shortLabel: 'Parents · après-midi',
    points: 6,
    type: 'check',
    section: 'relationships',
    icon: 'heart',
    hint: "Bilan de l'après-midi",
  },
  {
    id: 'parents-evening',
    label: 'Le soir, je respecte et ne provoque pas mes parents',
    shortLabel: 'Parents · soir',
    points: 6,
    type: 'check',
    section: 'relationships',
    icon: 'heart',
    hint: 'Bilan du soir',
  },
  {
    id: 'calm-corner',
    label: "Quand je sens la colère monter, je vais dans mon coin calme pour me détendre",
    shortLabel: 'Coin calme utilisé',
    points: 6,
    type: 'counter',
    section: 'counters',
    icon: 'leaf',
    hint: 'À chaque réussite',
  },
  {
    id: 'exceptional',
    label: 'Comportement exceptionnel',
    shortLabel: 'Comportement exceptionnel',
    points: 12,
    type: 'counter',
    section: 'counters',
    icon: 'star',
    hint: "À l'appréciation d'un adulte",
  },
];

export const DEFAULT_REWARDS: Reward[] = [
  { id: 'cards', title: 'Un paquet de cartes (ex. Pokémon)', cost: 50, emoji: '🃏' },
  { id: 'board-game', title: 'Un jeu de société avec Maman ou en famille', cost: 80, emoji: '🎲' },
  { id: 'video-game', title: '20 min de jeu vidéo', cost: 110, emoji: '🎮' },
  { id: 'dinner-choice', title: 'Choix du repas du soir en famille', cost: 130, emoji: '🍽️' },
  { id: 'chores-break', title: 'Un congé de tâches ménagères', cost: 150, emoji: '🌿' },
  { id: 'allowance', title: "5 euros d'argent de poche", cost: 180, emoji: '💶' },
  { id: 'tv-snack', title: 'Plateau apéro devant la télé', cost: 200, emoji: '🥨' },
  { id: 'fast-food', title: 'McDo', cost: 250, emoji: '🍔' },
  { id: 'friend-home', title: 'Inviter un copain à la maison', cost: 280, emoji: '🏠' },
  { id: 'activity', title: 'Une activité au choix (cinéma, laser game, trampoline…)', cost: 300, emoji: '🎯' },
  { id: 'surprise', title: "Cadeau surprise ou grande sortie (accrobranche, parc d'attractions…)", cost: 400, emoji: '🎁' },
];

export const DEFAULT_DATA: AppData = {
  version: 1,
  profile: {
    name: 'Sokhan',
    accent: '#317b69',
    highlight: '#e39a52',
  },
  days: {},
  rewards: DEFAULT_REWARDS,
  redemptions: [],
  updatedAt: new Date(0).toISOString(),
};

export const RELATIONSHIP_GROUPS = [
  {
    title: 'Avec mon frère et ma sœur',
    description: 'Je parle avec respect, sans surnom moqueur.',
    icon: 'users',
    ids: ['siblings-morning', 'siblings-afternoon', 'siblings-evening'],
  },
  {
    title: 'Avec mes parents',
    description: 'Je respecte et je ne provoque pas.',
    icon: 'heart',
    ids: ['parents-morning', 'parents-afternoon', 'parents-evening'],
  },
] as const;

export const PERIOD_LABELS = ['Matin', 'Après-midi', 'Soir'];

export const WEEKLY_ROWS = [
  { id: 'morning', label: 'Préparation du matin', behaviorIds: ['morning-ready'] },
  { id: 'homework', label: 'Devoirs sans rouspéter', behaviorIds: ['homework-calm'] },
  { id: 'meals', label: 'Repas calmes', behaviorIds: ['meal-breakfast', 'meal-lunch', 'meal-dinner'] },
  { id: 'obedience', label: 'Première demande', behaviorIds: ['obey-first'] },
  { id: 'objects', label: 'Soin des objets', behaviorIds: ['care-objects'] },
  { id: 'siblings', label: 'Respect de la fratrie', behaviorIds: ['siblings-morning', 'siblings-afternoon', 'siblings-evening'] },
  { id: 'parents', label: 'Respect des parents', behaviorIds: ['parents-morning', 'parents-afternoon', 'parents-evening'] },
  { id: 'calm', label: 'Coin calme', behaviorIds: ['calm-corner'] },
  { id: 'exceptional', label: 'Exceptionnel', behaviorIds: ['exceptional'] },
];
