import {
  BookOpen,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  CloudCheck,
  CloudOff,
  Coffee,
  Download,
  Gift,
  Heart,
  History,
  Home,
  ImagePlus,
  Leaf,
  LoaderCircle,
  Minus,
  Monitor,
  Moon,
  Mountain,
  Palette,
  Pencil,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Settings2,
  ShieldAlert,
  ShoppingBag,
  Sparkles,
  Star,
  Sun,
  Trash2,
  Trophy,
  Upload,
  UserRound,
  Users,
  Utensils,
  X,
  type LucideProps,
} from 'lucide-react';

const icons = {
  book: BookOpen,
  check: Check,
  'chevron-down': ChevronDown,
  left: ChevronLeft,
  right: ChevronRight,
  help: CircleHelp,
  saved: CloudCheck,
  offline: CloudOff,
  coffee: Coffee,
  download: Download,
  gift: Gift,
  heart: Heart,
  history: History,
  home: Home,
  image: ImagePlus,
  leaf: Leaf,
  loading: LoaderCircle,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  mountain: Mountain,
  palette: Palette,
  pencil: Pencil,
  plus: Plus,
  retry: RefreshCw,
  reset: RotateCcw,
  save: Save,
  settings: Settings2,
  shield: ShieldAlert,
  shop: ShoppingBag,
  sparkle: Sparkles,
  star: Star,
  sun: Sun,
  trash: Trash2,
  trophy: Trophy,
  upload: Upload,
  user: UserRound,
  users: Users,
  utensils: Utensils,
  close: X,
} as const;

export type IconName = keyof typeof icons;

interface IconProps extends LucideProps {
  name: IconName | string;
}

export function Icon({ name, ...props }: IconProps) {
  const Component = icons[name as IconName] ?? Sparkles;
  return <Component aria-hidden="true" strokeWidth={2.1} {...props} />;
}
